=== UKHomeOffice/booktravel_schema/travel-provider/TSP-60-ConfirmCancellation/TSP-60-ConfirmCancellation-Request.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "title": "TSP-60-Confirm Cancellation Request Schema",
  "version": "0.0.1",
  "description": "Schema for confirming cancellation of tickets. A message sent on this interface will always reference a single cancellation request. Multiple messages may be sent in response to a single cancellation request as the TSP may not cancel all tickets in one go.",
  "properties": {
    "requestId": {
      "type": "string",
      "description": "This is the unique return id created by HO when the request is first submitted by HO to TSP"
    },
    "bookingId": {
      "type": "string",
      "description": "Booking ID OR Itinerary Number issued by the GDS (Global distribution systems - travel networking systems used by travel agencies)"
    },
    "locator": {
      "$ref": "#/definitions/locatorDefinition"
    },
    "createdBy": {
      "$ref": "#/definitions/createdByDefinition",
      "description": "Details of the person who has actioned the cancellation."
    },
    "createdDateTime": {
      "description": "The time the request is created by CWT. Format is YYYY-MM-DDThh:mm:ss.",
      "type": "string",
      "pattern": "^\\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T(0[0-9]|1[0-9]|2[0-3]):(0[0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]):(0[0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])$"
    },
    "generalRemarks": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "requestId",
    "bookingId",
    "locator",
    "createdBy"
  ],
  "definitions": {
    "locatorDefinition": {
      "type": "object",
      "properties": {
        "locatorCode": {
          "description": "The Computer reservation system (CRS) creates a Record Locator also know as a PNR (Passenger Name Record) OR Booking Reference",
          "type": "string"
        },
        "lastName": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "locatorCode",
        "lastName"
      ],
      "additionalProperties": false
    },
    "createdByDefinition": {
      "type": "object",
      "description": "Basic contact details of the TSP Logger actioning this request",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the TSP logger who fulfilled the request and created the booking"
        },
        "email": {
          "type": "string",
          "description": "Email address of the logger.",
          "format": "email"
        },
        "telephone": {
          "type": "string",
          "description": "Phone number of the logger."
        },
        "groupName": {
          "type": "string",
          "description": "TSP Group name to contact if named contact not available.",
          "minLength": 1
        },
        "groupCode": {
          "type": "string",
          "description": "Code of the TSP contact group."
        },
        "groupEmail": {
          "type": "string",
          "description": "Email address of the TSP contact group.",
          "format": "email"
        },
        "groupTelephone": {
          "type": "string",
          "description": "Phone number of the TSP contact group.",
          "minLength": 1
        }
      },
      "additionalProperties": false,
      "required": [
        "groupName",
        "groupEmail",
        "groupTelephone"
      ]
    }
  }
}

=== UKHomeOffice/booktravel_schema/travel-provider/TSP-60-ConfirmCancellation/examples/0.0.1/TSP-60-Confirm-Cancellation.json
{
  "requestId": "2939314",
  "bookingId": "vivek9b5-c55a-4dce-8a8b-8c5473adbcfa",
  "locator": {
    "locatorCode": "OLD-VIV1",
    "lastName": "Kumar"
  },
  "createdBy": {
    "name": "CWT User",
    "email": "cwtuser@cwt.com",
    "telephone": "0209 843 9991",
    "groupName": "BRM-CWT",
    "groupEmail": "BRMCancel@cwt.com",
    "groupTelephone": "0209 843 9992",
    "groupCode": "BRM101111"
  },
  "createdDateTime": "2020-11-03T17:10:20",
  "generalRemarks": [
    "General Remark 1",
    "General Remark 2"
  ]
}
