=== UKHomeOffice/booktravel_schema/travel-provider/TSP-15-GetToken/TSP-15-GetToken-Response.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "TSP-15-GetToken Response Schema",
  "version": "0.0.1",
  "description": "Schema for authentication token response provided to TSP by RMP",
  "properties": {
    "access_token": {
      "type": "string",
      "description": "The access token to be used in subsequent API calls."
    },
    "expires_in": {
      "type": "integer",
      "description": "Number of seconds until the access token expires."
    },
    "refresh_expires_in": {
      "type": "integer",
      "description": "Number of seconds until the issued token expires."
    },
    "refresh_token": {
      "type": "string",
      "description": "A refresh token. Not relevant for CWT."
    },
    "token_type": {
      "type": "string",
      "description": "The type of access token provided.",
      "enum": [
        "bearer"
      ]
    },
    "id_token": {
      "type": "string",
      "description": "A token containing identifty information about the authetnicated party. Not relevant for CWT."

    },
    "not-before-policy": {
      "type": "integer",
      "description": "Unix timestamp in seconds before which this token will not be accepted. Not relevant for CWT."
    },
    "session_state": {
      "type": "string",
      "description": "A session state management identifier. Not relevant for CWT."

    }
  },
  "required": [
    "access_token",
    "expires_in"
  ]
}

=== UKHomeOffice/booktravel_schema/travel-provider/TSP-15-GetToken/examples/0.0.1/response.json
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSld.....",
  "expires_in": 36000,
  "refresh_expires_in": 1799,
  "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiS....",
  "token_type": "bearer",
  "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCI.....",
  "not-before-policy": 1519557697,
  "session_state": "715490d6-f79e-4330-a01d-d85c18a8fb10"
}
